local function giveItems()
    local player = getPlayer()

    local inv = player:getInventory()

    inv:AddItem("gunp.SemiShotgun")
    inv:AddItem("gunp.AR9mm")
    inv:AddItem("gunp.AR9Clip")
    inv:AddItem("gunp.AR9Clip")
    inv:AddItem("gunp.AR9Clip")
    inv:AddItem("Base.ShotgunShellsBox")
    inv:AddItem("Base.Bullets9mmBox")
    inv:AddItem("Base.Bullets9mmBox")
    inv:AddItem("Base.Bullets9mmBox")
    inv:AddItem("Base.Bullets9mmBox")
    inv:AddItem("Base.Bullets9mmBox")
    inv:AddItem("gunp.Model51")
    inv:AddItem("gunp.Bullets380Box")
    inv:AddItem("gunp.Bullets380Box")
    inv:AddItem("gunp.Model51Clip")
    inv:AddItem("gunp.Model51Clip")
    inv:AddItem("gunp.Model51Clip")
    inv:AddItem("gunp.Model51Clip") 
    inv:AddItem("gunp.Ruger44")
    inv:AddItem("Base.Bullets44Box")
    inv:AddItem("Base.Bullets44Box")
    inv:AddItem("Base.Bullets44Box")
    inv:AddItem("gunp.Beretta84fs")
    inv:AddItem("gunp.Bullets380Box")
    inv:AddItem("gunp.Bullets380Box")
    inv:AddItem("gunp.Beretta84Clip")
    inv:AddItem("gunp.Beretta84Clip")
    inv:AddItem("gunp.Beretta84Clip")
    inv:AddItem("gunp.Beretta84Clip") 
    inv:AddItem("gunp.RanchRifle")
    inv:AddItem("Base.223Box")
    inv:AddItem("Base.223Box")
    inv:AddItem("gunp.RanchRifleClip")
    inv:AddItem("gunp.RanchRifleClip")
    inv:AddItem("gunp.RanchRifleClip")
    inv:AddItem("gunp.RanchRifleClip") 
    inv:AddItem("gunp.RiotShotgun")
    
end

Events.OnGameStart.Add(giveItems)